# Generated by Django 2.0.5 on 2018-06-12 03:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='controller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training', models.CharField(blank=True, max_length=10)),
                ('autopilot', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='credentials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aws_access_key_id', models.CharField(max_length=256)),
                ('aws_secret_access_key', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='github',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='https://github.com/wroscoe/donkey', max_length=200)),
                ('extension', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tubs', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=50)),
                ('job_number', models.IntegerField(default=0)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('size', models.CharField(default='N/A', max_length=20)),
                ('instance_max', models.IntegerField(default=15)),
                ('request_time', models.IntegerField(default=2)),
                ('request_state', models.CharField(default='Pending', max_length=200)),
                ('availability_zone', models.CharField(default='...', max_length=200)),
                ('tarfile_size', models.CharField(default='N/A', max_length=20)),
                ('log_url', models.CharField(default='N/A', max_length=20)),
                ('commands_log_url', models.CharField(default='N/A', max_length=20)),
                ('duration', models.CharField(default='N/A', max_length=20)),
                ('instance', models.CharField(default='...', max_length=200)),
                ('request_id', models.CharField(default='0', max_length=200)),
                ('instance_id', models.CharField(default='0', max_length=200)),
                ('price', models.CharField(default='N/A', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='remarks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark', models.CharField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='jobs',
            name='Comments',
            field=models.ManyToManyField(to='console.remarks'),
        ),
    ]
