# Generated by Django 2.0.5 on 2018-07-11 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0002_auto_20180625_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='credentials',
            name='bucket_name',
            field=models.CharField(default='N/A', max_length=256),
        ),
    ]
