# Generated by Django 2.0.5 on 2018-07-16 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0003_credentials_bucket_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='facebook_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('JWT_token', models.CharField(max_length=256)),
                ('facebook_id', models.CharField(max_length=256)),
                ('name', models.CharField(max_length=256)),
                ('profile_picture_url', models.CharField(max_length=256)),
            ],
        ),
    ]
